### ISSUE TITLE
Please move and rename 

### ISSUE THREAD

**Issue by everett-toews** [rackspace/rackspace-ruby-sdk#6]
Looks like beloved is an OpenStack/Rackspace SDK. The repo doesn't really belong in this org.

When it gets moved out, the code base should be split into distinct OpenStack and Rackspace repos.

The OpenStack repo can live in an org in GitHub. Much like https://github.com/openstacknetsdk or https://github.com/gophercloud. The Rackspace repo must live at github.com/rackspace/rackspace-ruby-sdk.

I'd also highly recommend renaming the Gems built from those repos so it's very clear that they are for OpenStack and Rackspace to minimize user confusion.

**Comment by mdarby** [comment]
Moved. https://github.com/rackspace/rackspace-ruby-sdk
